// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
	}
	// JSONStoragesColumns holds the columns for the "json_storages" table.
	JSONStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "data", Type: field.TypeString, Size: 2147483647},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "creator_key", Type: field.TypeString, Default: "guest"},
	}
	// JSONStoragesTable holds the schema information for the "json_storages" table.
	JSONStoragesTable = &schema.Table{
		Name:       "json_storages",
		Columns:    JSONStoragesColumns,
		PrimaryKey: []*schema.Column{JSONStoragesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		JSONStoragesTable,
	}
)

func init() {
}
