// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"pocketjson/ent/jsonstorage"
	"pocketjson/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JsonStorageQuery is the builder for querying JsonStorage entities.
type JsonStorageQuery struct {
	config
	ctx        *QueryContext
	order      []jsonstorage.OrderOption
	inters     []Interceptor
	predicates []predicate.JsonStorage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JsonStorageQuery builder.
func (jsq *JsonStorageQuery) Where(ps ...predicate.JsonStorage) *JsonStorageQuery {
	jsq.predicates = append(jsq.predicates, ps...)
	return jsq
}

// Limit the number of records to be returned by this query.
func (jsq *JsonStorageQuery) Limit(limit int) *JsonStorageQuery {
	jsq.ctx.Limit = &limit
	return jsq
}

// Offset to start from.
func (jsq *JsonStorageQuery) Offset(offset int) *JsonStorageQuery {
	jsq.ctx.Offset = &offset
	return jsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jsq *JsonStorageQuery) Unique(unique bool) *JsonStorageQuery {
	jsq.ctx.Unique = &unique
	return jsq
}

// Order specifies how the records should be ordered.
func (jsq *JsonStorageQuery) Order(o ...jsonstorage.OrderOption) *JsonStorageQuery {
	jsq.order = append(jsq.order, o...)
	return jsq
}

// First returns the first JsonStorage entity from the query.
// Returns a *NotFoundError when no JsonStorage was found.
func (jsq *JsonStorageQuery) First(ctx context.Context) (*JsonStorage, error) {
	nodes, err := jsq.Limit(1).All(setContextOp(ctx, jsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jsonstorage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jsq *JsonStorageQuery) FirstX(ctx context.Context) *JsonStorage {
	node, err := jsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JsonStorage ID from the query.
// Returns a *NotFoundError when no JsonStorage ID was found.
func (jsq *JsonStorageQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = jsq.Limit(1).IDs(setContextOp(ctx, jsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jsonstorage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jsq *JsonStorageQuery) FirstIDX(ctx context.Context) string {
	id, err := jsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JsonStorage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JsonStorage entity is found.
// Returns a *NotFoundError when no JsonStorage entities are found.
func (jsq *JsonStorageQuery) Only(ctx context.Context) (*JsonStorage, error) {
	nodes, err := jsq.Limit(2).All(setContextOp(ctx, jsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jsonstorage.Label}
	default:
		return nil, &NotSingularError{jsonstorage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jsq *JsonStorageQuery) OnlyX(ctx context.Context) *JsonStorage {
	node, err := jsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JsonStorage ID in the query.
// Returns a *NotSingularError when more than one JsonStorage ID is found.
// Returns a *NotFoundError when no entities are found.
func (jsq *JsonStorageQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = jsq.Limit(2).IDs(setContextOp(ctx, jsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jsonstorage.Label}
	default:
		err = &NotSingularError{jsonstorage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jsq *JsonStorageQuery) OnlyIDX(ctx context.Context) string {
	id, err := jsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JsonStorages.
func (jsq *JsonStorageQuery) All(ctx context.Context) ([]*JsonStorage, error) {
	ctx = setContextOp(ctx, jsq.ctx, ent.OpQueryAll)
	if err := jsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JsonStorage, *JsonStorageQuery]()
	return withInterceptors[[]*JsonStorage](ctx, jsq, qr, jsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jsq *JsonStorageQuery) AllX(ctx context.Context) []*JsonStorage {
	nodes, err := jsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JsonStorage IDs.
func (jsq *JsonStorageQuery) IDs(ctx context.Context) (ids []string, err error) {
	if jsq.ctx.Unique == nil && jsq.path != nil {
		jsq.Unique(true)
	}
	ctx = setContextOp(ctx, jsq.ctx, ent.OpQueryIDs)
	if err = jsq.Select(jsonstorage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jsq *JsonStorageQuery) IDsX(ctx context.Context) []string {
	ids, err := jsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jsq *JsonStorageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jsq.ctx, ent.OpQueryCount)
	if err := jsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jsq, querierCount[*JsonStorageQuery](), jsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jsq *JsonStorageQuery) CountX(ctx context.Context) int {
	count, err := jsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jsq *JsonStorageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jsq.ctx, ent.OpQueryExist)
	switch _, err := jsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jsq *JsonStorageQuery) ExistX(ctx context.Context) bool {
	exist, err := jsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JsonStorageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jsq *JsonStorageQuery) Clone() *JsonStorageQuery {
	if jsq == nil {
		return nil
	}
	return &JsonStorageQuery{
		config:     jsq.config,
		ctx:        jsq.ctx.Clone(),
		order:      append([]jsonstorage.OrderOption{}, jsq.order...),
		inters:     append([]Interceptor{}, jsq.inters...),
		predicates: append([]predicate.JsonStorage{}, jsq.predicates...),
		// clone intermediate query.
		sql:  jsq.sql.Clone(),
		path: jsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Data string `json:"data,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JsonStorage.Query().
//		GroupBy(jsonstorage.FieldData).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jsq *JsonStorageQuery) GroupBy(field string, fields ...string) *JsonStorageGroupBy {
	jsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JsonStorageGroupBy{build: jsq}
	grbuild.flds = &jsq.ctx.Fields
	grbuild.label = jsonstorage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Data string `json:"data,omitempty"`
//	}
//
//	client.JsonStorage.Query().
//		Select(jsonstorage.FieldData).
//		Scan(ctx, &v)
func (jsq *JsonStorageQuery) Select(fields ...string) *JsonStorageSelect {
	jsq.ctx.Fields = append(jsq.ctx.Fields, fields...)
	sbuild := &JsonStorageSelect{JsonStorageQuery: jsq}
	sbuild.label = jsonstorage.Label
	sbuild.flds, sbuild.scan = &jsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JsonStorageSelect configured with the given aggregations.
func (jsq *JsonStorageQuery) Aggregate(fns ...AggregateFunc) *JsonStorageSelect {
	return jsq.Select().Aggregate(fns...)
}

func (jsq *JsonStorageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jsq); err != nil {
				return err
			}
		}
	}
	for _, f := range jsq.ctx.Fields {
		if !jsonstorage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jsq.path != nil {
		prev, err := jsq.path(ctx)
		if err != nil {
			return err
		}
		jsq.sql = prev
	}
	return nil
}

func (jsq *JsonStorageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JsonStorage, error) {
	var (
		nodes = []*JsonStorage{}
		_spec = jsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JsonStorage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JsonStorage{config: jsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (jsq *JsonStorageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jsq.querySpec()
	_spec.Node.Columns = jsq.ctx.Fields
	if len(jsq.ctx.Fields) > 0 {
		_spec.Unique = jsq.ctx.Unique != nil && *jsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jsq.driver, _spec)
}

func (jsq *JsonStorageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jsonstorage.Table, jsonstorage.Columns, sqlgraph.NewFieldSpec(jsonstorage.FieldID, field.TypeString))
	_spec.From = jsq.sql
	if unique := jsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jsq.path != nil {
		_spec.Unique = true
	}
	if fields := jsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jsonstorage.FieldID)
		for i := range fields {
			if fields[i] != jsonstorage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jsq *JsonStorageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jsq.driver.Dialect())
	t1 := builder.Table(jsonstorage.Table)
	columns := jsq.ctx.Fields
	if len(columns) == 0 {
		columns = jsonstorage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jsq.sql != nil {
		selector = jsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jsq.ctx.Unique != nil && *jsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jsq.predicates {
		p(selector)
	}
	for _, p := range jsq.order {
		p(selector)
	}
	if offset := jsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JsonStorageGroupBy is the group-by builder for JsonStorage entities.
type JsonStorageGroupBy struct {
	selector
	build *JsonStorageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jsgb *JsonStorageGroupBy) Aggregate(fns ...AggregateFunc) *JsonStorageGroupBy {
	jsgb.fns = append(jsgb.fns, fns...)
	return jsgb
}

// Scan applies the selector query and scans the result into the given value.
func (jsgb *JsonStorageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jsgb.build.ctx, ent.OpQueryGroupBy)
	if err := jsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JsonStorageQuery, *JsonStorageGroupBy](ctx, jsgb.build, jsgb, jsgb.build.inters, v)
}

func (jsgb *JsonStorageGroupBy) sqlScan(ctx context.Context, root *JsonStorageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jsgb.fns))
	for _, fn := range jsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jsgb.flds)+len(jsgb.fns))
		for _, f := range *jsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JsonStorageSelect is the builder for selecting fields of JsonStorage entities.
type JsonStorageSelect struct {
	*JsonStorageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jss *JsonStorageSelect) Aggregate(fns ...AggregateFunc) *JsonStorageSelect {
	jss.fns = append(jss.fns, fns...)
	return jss
}

// Scan applies the selector query and scans the result into the given value.
func (jss *JsonStorageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jss.ctx, ent.OpQuerySelect)
	if err := jss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JsonStorageQuery, *JsonStorageSelect](ctx, jss.JsonStorageQuery, jss, jss.inters, v)
}

func (jss *JsonStorageSelect) sqlScan(ctx context.Context, root *JsonStorageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jss.fns))
	for _, fn := range jss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
