// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pocketjson/ent/apikey"
	"pocketjson/ent/jsonstorage"
	"pocketjson/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[2].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescIsAdmin is the schema descriptor for is_admin field.
	apikeyDescIsAdmin := apikeyFields[3].Descriptor()
	// apikey.DefaultIsAdmin holds the default value on creation for the is_admin field.
	apikey.DefaultIsAdmin = apikeyDescIsAdmin.Default.(bool)
	jsonstorageFields := schema.JsonStorage{}.Fields()
	_ = jsonstorageFields
	// jsonstorageDescCreatorKey is the schema descriptor for creator_key field.
	jsonstorageDescCreatorKey := jsonstorageFields[3].Descriptor()
	// jsonstorage.DefaultCreatorKey holds the default value on creation for the creator_key field.
	jsonstorage.DefaultCreatorKey = jsonstorageDescCreatorKey.Default.(string)
}
